# This workflow will release a new version of this package if a new github release was created.

name: Release

on:
  release: 
    created: false
    
jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci 
    - run: make build
    - run: make test 
    - run: make release 
      env: 
         NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      
