# This workflow will release a new version of this package if a new github release was created.

name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org/
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: make build
      - run: make test
      - run: make release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
